[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
  { access = "read", path = "./deployments" },
  { access = "write", path = "./out" },
  { access = "read", path = "./contexts.json"}
]

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/816df2901a454b18b7df259e61f92cd2"
optimism = "https://mainnet.optimism.io"
arbitrum = "https://arb1.arbitrum.io/rpc"
avalanche = "https://api.avax.network/ext/bc/C/rpc"
polygon = "https://polygon-mainnet.infura.io/v3/816df2901a454b18b7df259e61f92cd2"

[fmt]
ignore = ["generated/**/*.sol", "lib/**/*.sol"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
